# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class NikeItem(scrapy.Item):
    # define the fields for your item here like:
    sku = scrapy.Field()
    uuid = scrapy.Field()
    url = scrapy.Field()
    activateCGCTest = scrapy.Field()
    athletes = scrapy.Field()
    availableSkus = scrapy.Field()
    brand = scrapy.Field()
    catalogId = scrapy.Field()
    category = scrapy.Field()
    collectionTermIds = scrapy.Field()
    colorDescription = scrapy.Field()
    commerceStartDate = scrapy.Field()
    conceptIds = scrapy.Field()
    countdown = scrapy.Field()
    currency = scrapy.Field()
    currentPrice = scrapy.Field()
    description = scrapy.Field()
    descriptionPreview = scrapy.Field()
    descriptionPreviewBullets = scrapy.Field()
    discounted = scrapy.Field()
    displayOrder = scrapy.Field()
    employeePrice = scrapy.Field()
    exclusiveAccess = scrapy.Field()
    firstImageAltText = scrapy.Field()
    firstImageUrl = scrapy.Field()
    fullPrice = scrapy.Field()
    fullTitle = scrapy.Field()
    genders = scrapy.Field()
    hardLaunch = scrapy.Field()
    isForNumberOfImagesABTesting = scrapy.Field()
    isLaunchView = scrapy.Field()
    isMinimumAdvertisedPrice = scrapy.Field()
    isNBYDesign = scrapy.Field()
    isNYBCountDown = scrapy.Field()
    isNikeID = scrapy.Field()
    jerseyIdPathName = scrapy.Field()
    langLocale = scrapy.Field()
    language = scrapy.Field()
    launchView = scrapy.Field()
    layoutCards = scrapy.Field()
    mainColor = scrapy.Field()
    mainPrebuild = scrapy.Field()
    marketing = scrapy.Field()
    marketplace = scrapy.Field()
    nbyContentCopy = scrapy.Field()
    nbyCustomMessage = scrapy.Field()
    nbyHubMessages = scrapy.Field()
    nikeIdStyleCode = scrapy.Field()
    nodes = scrapy.Field()
    notifyMeIndicator = scrapy.Field()
    origin = scrapy.Field()
    pathName = scrapy.Field()
    pid = scrapy.Field()
    piid = scrapy.Field()
    preOrder = scrapy.Field()
    prebuildId = scrapy.Field()
    preorderAvailabilityDate = scrapy.Field()
    productGroupId = scrapy.Field()
    productId = scrapy.Field()
    productRollup = scrapy.Field()
    productType = scrapy.Field()
    promoExclusionAccess = scrapy.Field()
    publishType = scrapy.Field()
    selectedSkuId = scrapy.Field()
    seoProductAvailability = scrapy.Field()
    seoProductDescription = scrapy.Field()
    seoProductReleaseDate = scrapy.Field()
    sizeAndFitDescription = scrapy.Field()
    sizeChartUrl = scrapy.Field()
    skus = scrapy.Field()
    sportTags = scrapy.Field()
    state = scrapy.Field()
    status = scrapy.Field()
    styleCode = scrapy.Field()
    styleColor = scrapy.Field()
    styleType = scrapy.Field()
    subTitle = scrapy.Field()
    sustainabilityMessage = scrapy.Field()
    threadId = scrapy.Field()
    title = scrapy.Field()
    updatedNBYDesignKey = scrapy.Field()
    useFeedsPromoExclusionMessage = scrapy.Field()
    vas = scrapy.Field()
    width = scrapy.Field()
    additionalInfo = scrapy.Field()
